### PR TITLE
Cookies wordsmithing, multiple authors

### PR DESCRIPTION
**Pull request by rbohl**
https://liferay.atlassian.net/browse/LPD-27286

I think I'm the last one, but there are still some blank "purpose" elements (I think @alec-shay is awaiting some feedback from his team):

`userTokenName`
`_ga`
`_gat_gtag_UA_`
`_gid`

The tickets assigned to me that actually needed work were

https://liferay.atlassian.net/browse/LPD-27308
https://liferay.atlassian.net/browse/LPD-27298

cc @alec-shay @aswinrajeevofficial @davidomontenegro @ericthmoritsuka

### CODE REVIEW

**Comment by Alec-Shay** [comment]
@sez11a , @rbohl I've finally got some confirmation on the values for the Google Analytics cookies, so I've got those descriptions ready too. I can provide those here, send those separately, or whatever works best. Just let me know. Thanks

**Comment by rbohl** [comment]
If you get them to me in the next 45 minutes @Alec-Shay  I can just push them into this PR (I assume that's the easiest way, if you want the commit-history-glory I can close this and send you the PR)

**Comment by DavidOMontenegro** [comment]
Commit history glory!!

**Comment by Alec-Shay** [comment]
@rbohl 

```
"name": "_gid",
"purpose": "Stores a unique ID to distinguish each user with Google Analytics. Statistics.",
```

```
"name": "_ga",
"purpose": "Stores a version number and a unique ID for the user's browser for tracking with Google Analytics. Statistics.",
```

```
"name": "_gat_gtag_UA_*",
"purpose": "Stores a random string value used to limit user requests. Statistics.",
```

That work? If it's easier I can also grab Aswin's branch and push on top of that.

**Comment by rbohl** [comment]
Pushed :rocket: 

The glory is mine :laughing: , but I credited you in the commit message :fist_right: :fist_left:

**Comment by sez11a** [comment]
Awesome job, @ericthmoritsuka , @DavidOMontenegro , @Alec-Shay , @aswinrajeevofficial , and @rbohl !!

Superseded by https://github.com/brianchandotcom/liferay-portal/pull/151162

**Pull request closed without merging**
