### PR TITLE
COMMERCE-8063 Talend Onboarding Docs wordsmithed

### PR DESCRIPTION
**Pull request by sez11a**
https://issues.liferay.com/browse/COMMERCE-8063

@igorbeslic

- COMMERCE-8063 talend - onboarding documentation improvement
- COMMERCE-8063 talend - source formatted
- COMMERCE-8063 Wordsmithing.

### CODE REVIEW

**Comment by sez11a** [comment]
ci:test

**Comment by sez11a** [comment]
ci:forward

**Comment by igorbeslic** [comment]
ci:forward

**Comment by sez11a** [comment]
ci:forward

**Pull request closed without merging**
