### PR TITLE
LPS-110309 Wordsmithed MFA Language Keys

### PR DESCRIPTION
**Pull request by sez11a**
@stian-sigvartsen

### CODE REVIEW

**Comment by sez11a** [comment]
ci:forward

**Comment by sez11a** [comment]
ci:forward

**Comment by sez11a** [comment]
ci:forward

**Comment by sez11a** [comment]
ci:forward

**Comment by yichenroy** [comment]
ci:forward

Forwarding again, the forward didn't happen because `ci:test:sf` didn't apply the passing status properly due to recent network outages.

-CI Infrastructure team.

**Pull request closed without merging**
